echo Uploading dhtnode2 to live memory nodes...
echo eq6-1...
cp ~/workspace/DhtNode/bin/dhtnode2 /mnt/eq6-1/srv/dht/memory-dht-1/
cp ~/workspace/DhtNode/bin/dhtnode2 /mnt/eq6-1/srv/dht/memory-dht-2/
echo eq6-2...
cp ~/workspace/DhtNode/bin/dhtnode2 /mnt/eq6-2/srv/dht/memory-dht-1/
cp ~/workspace/DhtNode/bin/dhtnode2 /mnt/eq6-2/srv/dht/memory-dht-2/
echo eq6-3...
cp ~/workspace/DhtNode/bin/dhtnode2 /mnt/eq6-3/srv/dht/memory-dht-1/
cp ~/workspace/DhtNode/bin/dhtnode2 /mnt/eq6-3/srv/dht/memory-dht-2/
echo eq6-4...
cp ~/workspace/DhtNode/bin/dhtnode2 /mnt/eq6-4/srv/dht/memory-dht-1/
cp ~/workspace/DhtNode/bin/dhtnode2 /mnt/eq6-4/srv/dht/memory-dht-2/
echo eq6-5...
cp ~/workspace/DhtNode/bin/dhtnode2 /mnt/eq6-5/srv/dht/memory-dht-1/
cp ~/workspace/DhtNode/bin/dhtnode2 /mnt/eq6-5/srv/dht/memory-dht-2/
echo eq6-6...
cp ~/workspace/DhtNode/bin/dhtnode2 /mnt/eq6-6/srv/dht/memory-dht-1/
cp ~/workspace/DhtNode/bin/dhtnode2 /mnt/eq6-6/srv/dht/memory-dht-2/
echo eq6-7...
cp ~/workspace/DhtNode/bin/dhtnode2 /mnt/eq6-7/srv/dht/memory-dht-1/
cp ~/workspace/DhtNode/bin/dhtnode2 /mnt/eq6-7/srv/dht/memory-dht-2/

