/*******************************************************************************

    Version information generated at compile time.

    copyright:      Copyright (c) 2011 sociomantic labs. All rights reserved

    version:        November 2011: Initial release

    authors:        Leandro Lucarella

    This file is automatically generated.

    DO NOT CHANGE, IT WILL BE OVERWRITTEN

    DO NOT ADD TO THE REPOSITORY

*******************************************************************************/

module src.main.Version;

private import ocean.util.Main;

public VersionInfo Version;

static this()
{
    // TODO: Version.release = "@RELEASE@";
    Version.revision     = "r9184:9203M";
    Version.gc           = "cdgc";
    Version.build_date   = "2012-03-07";
    Version.build_author = "gavin";
    Version.libraries["tango"] = "r3753";
    Version.libraries["ocean"] = "r3758:3759";
    Version.libraries["swarm"] = "r3752:3757";

}

// vim: set filetype=d :
